[package]
name = "keccak"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
ark-bn254.workspace = true
keccak.workspace = true
gkr = { path = "../gkr" }

[build-dependencies]
cbindgen.workspace = true 