[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
blake3.workspace = true
hex.workspace = true
keccak.workspace = true
gkr = { path = "../gkr", default-features = false }
rayon.workspace = true
tracing.workspace = true
tracing-forest.workspace = true

[features]
default = ["whir"]
whir = ["gkr/whir"]
