name: CI

on:
  push:
    branches: [main]
    paths:
      - 'rust/**'
      - 'gnark/**'
  pull_request:
    branches: [main]
    paths:
      - 'rust/**'
      - 'gnark/**'

jobs:
  rust_fmt:
    name: Rust Format Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  rust_clippy:
    name: Rust Clippy Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust_test:
    name: Rust Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --all

  go:
    name: Go CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gnark
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check formatting
        run: go fmt ./...

      - name: Vet code
        run: go vet ./...

      - name: Run tests
        run: go test ./...
